package ar.com.sicos.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import ar.com.cxf.matematica.OperacionesMatematicas;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-11-03T08:25:57.949-03:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "OperacionesMatematicasImplService",
                  wsdlLocation = "file:/home/raman01/JAVA%20BOOTCAMP/EXAMPLES/CLASE-08/ClientSoap/src/main/resources/wsdl/operaciones.wsdl",
                  targetNamespace = "http://service.sicos.com.ar/")
public class OperacionesMatematicasImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.sicos.com.ar/", "OperacionesMatematicasImplService");
    public final static QName OperacionesMatematicasImplPort = new QName("http://service.sicos.com.ar/", "OperacionesMatematicasImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/operaciones?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OperacionesMatematicasImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/raman01/JAVA%20BOOTCAMP/EXAMPLES/CLASE-08/ClientSoap/src/main/resources/wsdl/operaciones.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OperacionesMatematicasImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OperacionesMatematicasImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperacionesMatematicasImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OperacionesMatematicasImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OperacionesMatematicasImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OperacionesMatematicasImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OperacionesMatematicas
     */
    @WebEndpoint(name = "OperacionesMatematicasImplPort")
    public OperacionesMatematicas getOperacionesMatematicasImplPort() {
        return super.getPort(OperacionesMatematicasImplPort, OperacionesMatematicas.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OperacionesMatematicas
     */
    @WebEndpoint(name = "OperacionesMatematicasImplPort")
    public OperacionesMatematicas getOperacionesMatematicasImplPort(WebServiceFeature... features) {
        return super.getPort(OperacionesMatematicasImplPort, OperacionesMatematicas.class, features);
    }

}
