
package ar.com.cxf.matematica;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-11-07T18:54:32.622-03:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "DivisionPorCero", targetNamespace = "http://cxf.com.ar/matematica")
public class DivisionPorZeroException extends Exception {

    private DivisionPorCero faultInfo;

    public DivisionPorZeroException() {
        super();
    }

    public DivisionPorZeroException(String message) {
        super(message);
    }

    public DivisionPorZeroException(String message, Throwable cause) {
        super(message, cause);
    }

    public DivisionPorZeroException(String message, DivisionPorCero divisionPorCero) {
        super(message);
        this.faultInfo = divisionPorCero;
    }

    public DivisionPorZeroException(String message, DivisionPorCero divisionPorCero, Throwable cause) {
        super(message, cause);
        this.faultInfo = divisionPorCero;
    }

    public DivisionPorCero getFaultInfo() {
        return this.faultInfo;
    }
}
